"""
warning: autogenerated by writefile2. do not edit!
"""

import require
from tqdm import tqdm
import sys
import nodes
from IPython.display import display, HTML

"""
collects training data from a selection of countries as a list of dataframes

Note: by cropping here we loose some data (temporally), 
but we use the dataframe for window processing and need NaN-free series
"""

#TODO: can be replaced by cached nodes
compute_data_for_country = require.single( "compute_data_for_country" )
crop_to_valid_range = require.single( "crop_to_valid_range" )
verbose = require.untracked.single( "verbose" )
owid_countries = require.single( "countries_in_owid" )
oxford_countries = require.single( "countries_in_oxford" )
broken_countries = require.single( "countries_known_to_be_broken" )

def compute_training_data( ):

    countries = list( set( owid_countries ).intersection( oxford_countries ).difference( broken_countries ))
    
    if verbose( ):

        display( HTML( f"<h1>Training data</h1>" ))
        print( countries )
    
    dataframes = [ ]

    for country in tqdm( countries, file = sys.stdout, desc = "collecting data" ):
        
        if verbose( ):
        
            display( HTML( f"<h3>{ country }</h3>" ))

        df = compute_data_for_country( country )
        df = crop_to_valid_range( df ).copy( ) 
        dataframes.append( df )

    return dataframes
        
