"""
countries in the OWID (our world in data) data set. some of these are not actually countries, 
but the algorithm does not care about that.
"""


countries_in_owid = ['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
   'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda',
   'Argentina', 'Armenia', 'Aruba', 'Asia', 'Australia', 'Austria',
   'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
   'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
   'Bolivia', 'Bonaire Sint Eustatius and Saba',
   'Bosnia and Herzegovina', 'Botswana', 'Brazil',
   'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
   'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
   'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
   'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
   'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
   'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
   'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
   'El Salvador', 'England', 'Equatorial Guinea', 'Eritrea',
   'Estonia', 'Eswatini', 'Ethiopia', 'Europe', 'European Union',
   'Faeroe Islands', 'Falkland Islands', 'Fiji', 'Finland', 'France',
   'French Guiana', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
   'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
   'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea',
   'Guinea-Bissau', 'Guyana', 'Haiti', 'High income', 'Honduras',
   'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
   'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica',
   'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
   'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
   'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
   'Low income', 'Lower middle income', 'Luxembourg', 'Macao',
   'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
   'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
   'Mayotte', 'Mexico', 'Micronesia (country)', 'Moldova', 'Monaco',
   'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
   'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
   'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
   'Niue', 'North America', 'North Korea', 'North Macedonia',
   'Northern Cyprus', 'Northern Ireland', 'Northern Mariana Islands',
   'Norway', 'Oceania', 'Oman', 'Pakistan', 'Palau', 'Palestine',
   'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
   'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
   'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Barthelemy',
   'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
   'Saint Martin (French part)', 'Saint Pierre and Miquelon',
   'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
   'Sao Tome and Principe', 'Saudi Arabia', 'Scotland', 'Senegal',
   'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
   'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
   'Solomon Islands', 'Somalia', 'South Africa', 'South America',
   'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
   'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
   'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tokelau',
   'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
   'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda',
   'Ukraine', 'United Arab Emirates', 'United Kingdom',
   'United States', 'United States Virgin Islands',
   'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu',
   'Vatican', 'Venezuela', 'Vietnam', 'Wales', 'Wallis and Futuna',
   'Western Sahara', 'World', 'Yemen', 'Zambia', 'Zimbabwe']