"""
countries which produced an acceptable (positive) per-time-series r2 score in the train set.
if a country is in the train set and produces a negative r2 score, we consider it harmful for the model.
this was tested on the honest_forward model with n_estimators = 100, max_depth = 20, max_features = 1.0,length_l = 100, lag = 50
trained on 80% of the dataset: list( set( owid_countries ).intersection( oxford_countries ).difference( broken_countries ))
"""

countries_with_high_r2 = [

'Albania',
 'Andorra',
 'Argentina',
 'Austria',
 'Bahamas',
 'Bahrain',
 'Belgium',
 'Belize',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Canada',
 'Chile',
 'Colombia',
 'Croatia',
 'Cyprus',
 'Denmark',
 'Ecuador',
 'Estonia',
 'Faeroe Islands',
 'Finland',
 'France',
 'Georgia',
 'Germany',
 'Guyana',
 'Hungary',
 'Iran',
 'Ireland',
 'Israel',
 'Italy',
 'Kosovo',
 'Liechtenstein',
 'Luxembourg',
 'Malta',
 'Mexico',
 'Netherlands',
 'Norway',
 'Palestine',
 'Paraguay',
 'Peru',
 'Poland',
 'Portugal',
 'Romania',
 'Slovenia',
 'Sweden',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Ukraine',
 'United States',
 'United States Virgin Islands',
 'Uruguay',

 'Latvia',
 'Lithuania',
 'Moldova',
 'Serbia',
 'Switzerland',
 'Suriname',
 'Panama',
 'Spain',
 'United Kingdom',
 'Greece'
 ]