#mainly due to missing outcomes, no testing data or overall sketchy looking data

countries_known_to_be_broken = [

   "Macao",
   "Turkmenistan",
   "Burundi",
   "Tajikistan",
   "Taiwan",
   "South Sudan",
   "Oman",
   "Venezuela",
   "Kiribati",
   "Greenland",
   "Qatar",
   "Monaco",
   "Brunei",
   "Bermuda",
   "Hong Kong",
   "Central African Republic",
   "Burkina Faso",
   "Lesotho",
   "Guinea",
   "Gambia",
   "Barbados",
   "Syria",
   "Congo",
   "San Marino",
   "Yemen",
   "Honduras",
   "Egypt",
   "Gabon",
   "Sudan",
   "Benin",
   "Liberia",
   "Eswatini",
   "Djibouti",
   "Somalia",
   "Papua New Guinea",
   "Libya",
   "Grenada",
   "Faroe Islands"
   "Chile",
   "Niger",
   "Nicaragua",
   "Comoros",
   "Angola",
   "Algeria",
   "Dominica",
   "Eritrea",
   "Mauritius",
   "Aruba",
   "Tonga",
   "Sierra Leone",
   "Vanuatu",
   "Singapore",
   "Uzbekistan",
   "Mali",
   "Chad",
   "Seychelles",
   "Solomon Islands",
   "Lebanon",
   "Guam",
   "Tanzania",
   "Cape Verde",
   "Afghanistan"

]