"""
warning: autogenerated by writefile2. do not edit!
"""


"""
using get_valid_range.py, crop the data frame and forward-fill intermediate nan values.
when interactively used, warn the user if filling was necessary.
"""

import pandas as pd
from IPython.display import display, HTML
import require
get_valid_range = require.single( "get_valid_range" )
verbose = require.untracked.single( "verbose" )

def crop_to_valid_range( df ):

    df = df.iloc[ get_valid_range( df ), : ]
    
    # Check if DataFrame has any NaN values
    for col, sum in df.isna( ).sum( ).items( ):

        if sum > 0:

            if verbose( ) >= 1:
                
                display( HTML( f"<p>warning '{ col }' has { sum } nan(s). performed forward fill.</p>" ))

    df = pd.DataFrame.fillna( df, axis = 0, method = "ffill" )
    assert not df.isna( ).any( ).any( )
    
    return df
    
