"""
warning: autogenerated by writefile2. do not edit!
"""


import pandas as pd
from IPython.display import display, HTML
import require
get_valid_range = require.single( "get_valid_range" )

def crop_to_valid_range( df, verbose = 1 ):

    df = df.iloc[ get_valid_range( df, verbose = verbose ), : ]
    
    # Check if DataFrame has any NaN values
    for col, sum in df.isna( ).sum( ).items( ):

        if sum > 0:

            if verbose >= 1:
                
                display( HTML( f"<p>warning '{ col }' has { sum } nan(s). performed forward fill.</p>" ))

    df = pd.DataFrame.fillna( df, axis = 0, method = "ffill" )
    assert not df.isna( ).any( ).any( )
    
    return df
    
