"""
warning: autogenerated by writefile2. do not edit!
"""


"""
caching node with little additional logic, wrapping compute_data_for_country.py
"""

import nodes
import require

@nodes.generic_node
def data_for_country( country, categorical_as_dummy = True ):

    compute_data_for_country = require.single( "compute_data_for_country" )
    
    if categorical_as_dummy:

        categorical_to_dummy = require.single( "categorical_to_dummy" )
        
        def main( raw: data_for_country.given( country, categorical_as_dummy = False )):

            return categorical_to_dummy( raw.result )

        return main
        
    else:

        return lambda: compute_data_for_country( country, categorical_as_dummy = False )

node = data_for_country
