"""
warning: autogenerated by writefile2. do not edit!
"""


import datetime
import pandas as pd
import numpy as np

def get_oxford_df( file, country ):

    df = pd.read_csv( file )
    df = df[ df.country_name == country ]
    df = df[ df.region_code.to_numpy( dtype = str ) == "nan" ]
    
    df_t = df.T
    
    dates = list( df_t.index[ 6: ])
    
    # Given list of strings representing dates
    dates = [ datetime.datetime.strptime( date, "%d%b%Y" ).strftime( "%Y-%m-%d" ) for date in dates ]
    
    # Convert the list of strings to a DateTimeIndex
    datetime_index = pd.to_datetime(dates)
    
    # Given list of values for the "Germany" column
    country_values = df_t.iloc[ 6:, : ]
    
    df_country = country_values
    
    # Create the DataFrame
    df_country.index = datetime_index
    df_country.columns = [ "series" ]

    return df_country    
