"""
warning: autogenerated by writefile2. do not edit!
"""

import require
from tqdm import tqdm
import sys
from IPython.display import display, HTML

"""
Note: by cropping here we loose some data (temporally), 
but we use the dataframe for window processing and need NaN-free series
"""

get_data_for_country = require.single( "get_data_for_country" )
crop_to_valid_range = require.single( "crop_to_valid_range" )

def get_training_data( verbose = 1 ):

    if verbose == False:

        verbose = 0

    if verbose >= 1:

        display( HTML( f"<h1>Training data</h1>" ))
    
    dataframes = [ ]
    
    for country in tqdm([ "Germany", "Switzerland", "Italy", "France", "Belgium", "United States", "Spain", "United Kingdom", "Malaysia", "South Korea", "Chile" ], file = sys.stdout ):

        if verbose >= 1:
        
            display( HTML( f"<h3>{ country }</h3>" ))

        df = get_data_for_country( country, verbose = verbose >= 2 )
        df = crop_to_valid_range( df, verbose = verbose ).copy( ) 
        dataframes.append( df )

    return dataframes
        
