"""
warning: autogenerated by writefile2. do not edit!
source: window_patches_h.ipynb
"""


"""
get the number of window samples resulting from a dataframe using given window lengths and lag
"""

def get_number_of_window_samples( df, length_l, lag, length_r ):
    
    return df.shape[ 0 ] - length_l - lag - length_r + 1
