"""
warning: autogenerated by writefile2. do not edit!
source: typed_h.ipynb
"""


# do not import with 'require'
import inspect
from collections import OrderedDict

def signature_match_args( f, args, kwargs ):
    
    argspec = inspect.getfullargspec( f )
    defaults = ( ) if argspec.defaults is None else argspec.defaults
    positional_arg_count = len( argspec.args ) - len( defaults )
    missing_arg_count = positional_arg_count - len( args )
    if missing_arg_count > 0:
        
        args = ( * args, *( [ None ] * missing_arg_count ))
        
    args_dict = OrderedDict( zip( argspec.args[ :positional_arg_count], args ))
    args_dict.update( OrderedDict( zip( argspec.args[ positional_arg_count: ], defaults )))
    args_dict.update( kwargs )
    return args_dict
