"""
warning: autogenerated by writefile2. do not edit!
"""

import nodes
import require

@nodes.generic_node
def training_data( ):

    get_training_data = require.single( "get_training_data" )
    
    def main( ):

        return get_training_data( verbose = 0 )

    return main
    
