"""
warning: autogenerated by writefile2. do not edit!
source: training_data_h.ipynb
"""


"""
cache node wrapper around compute_training_data.py
"""

import nodes
import require

@nodes.store_in_tmp
@nodes.generic_node
def training_data( ):

    compute_training_data = require.single( "compute_training_data" )
    
    def main( ):

        return compute_training_data( )

    return main

node = training_data
