"""
warning: autogenerated by writefile2. do not edit!
"""


"""
cache node wrapper around ensemble.py and training_data.py that caches the trained model
"""

import nodes
import require

@nodes.generic_node
def train_ensemble( ):

    ensemble = require.single( "ensemble" )
    training_data_node = require.single( "training_data" )
    
    def main( training_data: training_data_node.given( )):

        e = ensemble( )
        e.train( training_data.result )
        return e

    return main

node = train_ensemble
